### ISSUE TITLE
Change size of fileshare afterwards

### ISSUE THREAD

**Issue by peevishkiwi** [mrfenyx/RPi-Zero-W-WiFi-USB#3]
Not an issue, a question! 
First of all, thank you for sharing. This makes my life much easier as my printer is located in another room.

I choose the automatic installation and it worked great. Now i am just wondering if it is possible to change the size of the fileshare afterwards from count=2048 to count=4096 for example. 
Did some reasearch bit did not find anything which would help. Or do i need to reinstall using the manual way?

**Comment by mrfenyx** [comment]
Hi, I have not tried it myself yet but maybe this can help: https://superuser.com/questions/693158/can-i-expand-the-size-of-a-file-based-disk-image

**Comment by peevishkiwi** [comment]
Thanks for the link! 
Using the command "dd if=/dev/zero bs=1 count=4096 >> ./piusb.bin" from your link i was able to make the .bin bigger. 
This was verified using the other commands from the forum. However the share is still 2GB. I restarted the PI and also tried formating it again, still shows 2GB. Last thing i tried was to unmount the share and remount it --> Windows is still showing 2GB.

Will try to experiment a bit in the next days. Seems to be way more complex than expected.
