### ISSUE TITLE
Raspberry pi has updated the /boot/cmdline location.

### ISSUE THREAD

**Issue by cropse** [mrfenyx/RPi-Zero-W-WiFi-USB#4]
Try to locate the boot/cmdline.txt
and found the description below:
```
DO NOT EDIT THIS FILE

The file you are looking for has moved to /boot/firmware/cmdline.txt modules-load=dwc2
```
Maybe change this line to fix it?
https://github.com/mrfenyx/RPi-Zero-W-WiFi-USB/blob/e828cecc8f1597d2cd2d2cea000e319f9bd8955a/install.sh#L111

As file to /boot/firmware/config.txt.
It happened in 2024/3/14 relased raspberry pi OS.

**Comment by mrfenyx** [comment]
Added check to the script: use new location if it exists, old one if not.
