### ISSUE TITLE
New feature request "http upload with username and password"

### ISSUE THREAD

**Issue by raindancer2204** [mrfenyx/RPi-Zero-W-WiFi-USB#5]
Hello, your Samba USB stick is really great. But isn't there still the possibility of building an http frontend where you log in with a username and password and carry out the "upload" and delete? Then you would have 2 options. I'm a little spoiled by the "Octoprint" track. But unfortunately that no longer works with my new printer :(

**Comment by mrfenyx** [comment]
Hi, I'm sorry but I meant this as a very basic tool to avoid moving the USB from PC to printer. Currently, I don't plan of implementing any type of frontend for it as file operations can be done easily while the drive is mounted as a network device.
