### ISSUE TITLE
Network share works, but not USB

### ISSUE THREAD

**Issue by Jollejeppe** [mrfenyx/RPi-Zero-W-WiFi-USB#6]
Hi @mrfenyx 

I'm a complete noob when it comes to Linux and Raspberry Pi, so I'm sorry if it's me who's stupid.

I have a Raspberry Pi Zero 2 W and used the automated setup, with seemingly no problems.
The OS is Raspberry Pi OS Lite 32-bit released 2024-07-04.
I can access the network storage through Wi-Fi, but neither my PC or Anycubic Kobra 2 Pro can detect it using the USB-port.
At first I used a modified USB-cable and tried a new one, but no luck.
The USB-port works when using a keyboard.
I formated the SD-card and did the setup from scratch another time, but the result was the same.

Is there perhaps something I missed during the setup?

**Comment by mrfenyx** [comment]
Hi, the only thing I can think of is indeed the USB cable, where you need to make sure you correctly modify it. I've tried the script on a zero w and a zero 2 w and it works on both but the cable was crucial.

**Comment by Jollejeppe** [comment]
I finally got it to work! It seems like the "sudo apt upgrade -y" command was the problem for me.
When I tried the automated setup without upgrading it worked immediately.
